name: tc-portal-educacional

services:
  mongo:
    image: mongo:7.0
    container_name: tc-portal-educacional-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: ./backend
    container_name: tc-portal-educacional-app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/blogdb
      # se usar JWT:
      JWT_SECRET: devsecret
      JWT_EXPIRES_IN: 7d
    depends_on:
      - mongo

  front:
    build:
      context: ./frontend
      args:
        # o front vai chamar o backend pelo nome do serviço ("app")
        VITE_API_URL: http://localhost:3000/api
    container_name: tc-portal-educacional-front
    ports:
      - "8080:80"
    depends_on:
      - app

volumes:
  mongo_data:
