name: ci/cd - teste e docker deploy
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: testes
    runs-on: ubuntu-latest

    steps:
      - name: checkout do repo
        uses: actions/checkout@v4

      - name: Config node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: instalar dependncias
        run: npm ci

      - name: rodar testes com mongo em memória
        run: npm test -- --detectOpenHandles --forceExit --verbose

  deploy:
    name: deploy docker hub
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && success()

    steps:
      - name: checkout do repo
        uses: actions/checkout@v4

      - name: login 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: build e push da imagem
        run: |
          docker build \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/petech-stock:latest \
            --build-arg MONGO_URI=${{ secrets.DATABASE_URL }} \
            .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/petech-stock:latest
