name: tc-portal-educacional

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-ci:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Subir containers do app
        run: docker compose up -d --build

      - name: Executar testes
        run: docker compose run --rm app npm test -- --detectOpenHandles --forceExit --verbose

      - name: Derrubar containers
        run: docker compose down
